import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "./providers";
import Toploader from "nextjs-toploader";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex min-h-[calc(100vh-1px)] flex-col antialiased`}
      >
        <Toploader color="#4B76C9" showSpinner={false} height={2.8} />
        <main className="relative flex flex-1 flex-col">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
